[package]
name = "echo-node"
version = "0.1.0"
edition = "2021"

[dependencies]
serde =  { version = "1.0",features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "sync"] }
maelstrom-node = {path="../maelstrom-node"}
